spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}


admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
admin.email=${ADMIN_EMAIL:}
admin.password=${ADMIN_PASSWORD:}
admin.name=${ADMIN_NAME:CERN Administrator}
admin.phone=${ADMIN_PHONE:}
server.port=${PORT:8080}